"""User full name, school

Revision ID: 1932a7ed534
Revises: 26bcce87028
Create Date: 2015-03-27 03:11:29.386708

"""

# revision identifiers, used by Alembic.
revision = '1932a7ed534'
down_revision = '26bcce87028'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.Unicode(), nullable=False))
    op.add_column('users', sa.Column('school', sa.String(length=2), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'school')
    op.drop_column('users', 'full_name')
    ### end Alembic commands ###
