"""initial (empty) models

Revision ID: 26bcce87028
Revises: 
Create Date: 2015-03-25 03:14:29.779647

"""

# revision identifiers, used by Alembic.
revision = '26bcce87028'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_resources_owner_group_id'), 'resources', ['owner_group_id'], unique=False)
    op.create_index(op.f('ix_resources_owner_user_id'), 'resources', ['owner_user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_owner_user_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_owner_group_id'), table_name='resources')
    ### end Alembic commands ###
